service: daily-training-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: '{proxy+}'
          method: any
          cors: true
